[package]
name = "cyber-pumpkin-scheduler"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
cyber-pumpkin-operations = { path = "../cyber-pumpkin-operations" }

[lints]
workspace = true
