[package]
name = "cyber-pumpkin-secrets"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "3.7.0"

[lints]
workspace = true
