[package]
name = "cyber-pumpkin-sftp"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
cyber-pumpkin-backend = { path = "../../filesystem/cyber-pumpkin-backend" }
cyber-pumpkin-core = { path = "../../foundation/cyber-pumpkin-core" }
ssh2 = { version = "0.9.6", features = ["vendored-openssl"] }

[lints]
workspace = true
