[package]
name = "cpk"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
cyber-pumpkin-application = { path = "../../sdk/application/cyber-pumpkin-application" }
cyber-pumpkin-backend = { path = "../../sdk/filesystem/cyber-pumpkin-backend" }
cyber-pumpkin-core = { path = "../../sdk/foundation/cyber-pumpkin-core" }
cyber-pumpkin-local = { path = "../../sdk/filesystem/cyber-pumpkin-local" }
cyber-pumpkin-sftp = { path = "../../sdk/ssh/cyber-pumpkin-sftp" }
cyber-pumpkin-sync-plan = { path = "../../sdk/sync/cyber-pumpkin-sync-plan" }
cyber-pumpkin-sync = { path = "../../sdk/sync/cyber-pumpkin-sync" }
cyber-pumpkin-reliability = { path = "../../sdk/reliability/cyber-pumpkin-reliability" }
cyber-pumpkin-transfer = { path = "../../sdk/transfer/cyber-pumpkin-transfer" }

[lints]
workspace = true
