[package]
name = "cpk"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
cyber-pumpkin-backend = { path = "../../sdk/filesystem/cyber-pumpkin-backend" }
cyber-pumpkin-core = { path = "../../sdk/foundation/cyber-pumpkin-core" }
cyber-pumpkin-local = { path = "../../sdk/filesystem/cyber-pumpkin-local" }
cyber-pumpkin-sftp = { path = "../../sdk/ssh/cyber-pumpkin-sftp" }
cyber-pumpkin-transfer = { path = "../../sdk/transfer/cyber-pumpkin-transfer" }

[lints]
workspace = true
